### ISSUE TITLE
Error defining mask in utils.py

### ISSUE THREAD

**Issue by trearick** [matejak/imreg_dft#33]
In imreg_dft/src/imreg_dft/utils.py, line 710-713, you define a border mask of with radius:
    mask[:, :radius] = True
    mask[:, -radius:] = True
    mask[radius, :] = True
    mask[-radius:, :] = True
However, line 712 is incorrect as it masks a single row (radius) not a span (:radius).

**Comment by matejak** [comment]
Great catch, thanks!
