### ISSUE TITLE
Multichannel  Images

### ISSUE THREAD

**Issue by jn31** [matejak/imreg_dft#34]
Hello, 
I am trying to use your library for registration of a series of 13 images. They have four channels (RGB + IR). When i use the similarity func. on all four channels they all have slightly different translation and rotation results. Could it be possible to just calculate the transformation data on all 4 channels without actually transforming them (would save time) and then choose a transformation of a single channel (the one with the best success rate) and apply it to all 4 ? The  4 channels would then align when they are written to a single image. 

Could you also please define the success rate ? How is it calculated ?

Nice Greetings, Jure

**Comment by akatav** [comment]
hi @jn31 can you please post your code here ? i am trying to get imreg_dft working for a similar problem too (4 channels, 3d stack of images) but i get an error - Images must have the same shape.

**Comment by jn31** [comment]
Hello!

I have had multiple 4 channel images (R,G,B,IR). For the imreg_dfr similarity function you have to choose one of the color channels to run on. So i just used the function:

`result = ird.similarity(template_img[0], subject_img[0]], numiter=1, order=1)`

Where` template_img[0]` and` subject_img[0]` are **2D numpy arrays**.

```
template_img.shape=(N,y,x)
template_img[0].shape=(y,x)
```
Where N is number of channels, y numbers of rows and x number of collums.

Out of the similarity function you get a `result` dictionary with the scale, translation and rotation values. Then you transform all of the 4 channels with the same paramaters:
```
subject_img[0]= ird.transform_img(subject_img[0], scale=result['scale'], angle=result['angle'], tvec=result['tvec'], mode='constant', bgval=0, order=1)
subject_img[1]= ird.transform_img(subject_img[1], scale=result['scale'], angle=result['angle'], tvec=result['tvec'], mode='constant', bgval=0, order=1)
subject_img[2]= ird.transform_img(subject_img[2], scale=result['scale'], angle=result['angle'], tvec=result['tvec'], mode='constant', bgval=0, order=1)
subject_img[3]= ird.transform_img(subject_img[3], scale=result['scale'], angle=result['angle'], tvec=result['tvec'], mode='constant', bgval=0, order=1)
```
I dont know your code, but the shape issue could come from not taking just one channel for either template or subject image or one image has a 3d shape and not a 2d shape. 

The result vary based on the choice of the color channel (it must be the same channel on both images) so test which gives best results in your case.

So one more time, the fist two arguments of the similarity function are **2d numpy** arrays presenting the same  color channel in both images.

Nice grettings!

**Comment by matejak** [comment]
The success correlates with the contrast in the power spectrum. See [_get_success](https://github.com/matejak/imreg_dft/blob/master/src/imreg_dft/utils.py#L262). And yes, you have correctly found out that you can use the `similarity` function and the succes, which is part of its result.
